### ISSUE TITLE
This function always gives a syntax error.

### ISSUE THREAD

**Issue by shaaaarpy** [esantorella/hdfe#3]
Hi 
I am trying to use this library but i am always getting a syntax error.

result[self.keys_as_int[k]] = function(vector[idx])
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by esantorella** [comment]
Could you provide a minimal working example so that I can reproduce this error?

**Comment by shaaaarpy** [comment]
Can you please confirm if your package is python2 or 3?

**Comment by esantorella** [comment]
I have only tested it with Python 3.

**Comment by shaaaarpy** [comment]
working with both python2 and 3
