### ISSUE TITLE
numpy function parameters

### ISSUE THREAD

**Issue by shaaaarpy** [esantorella/hdfe#5]
Hi 
I want to use np.std over groupby and want to change the default value of ddof used in np.std.
Is this possible.

Thank you

**Comment by esantorella** [comment]
You've probably solved this by now, but just in case it's helpful: Say you want to use `ddof=my_ddof_val`. define a function `f = lambda x: np.std(x, ddof=my_ddof_val)` and pass `f` to `Groupby.apply` rather than `np.std`
